import jsPDF from 'jspdf';
import type { HardwareInfo, PowerData, CostBreakdown, TnbTariffBlock } from '../types';

export function exportToPdf(
  hw: HardwareInfo,
  power: PowerData,
  cost: CostBreakdown,
  tariffName: string,
  blocks: TnbTariffBlock[]
) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 20;

  doc.setFontSize(20);
  doc.setTextColor(147, 51, 234);
  doc.text('Consumptioness - PC Power Report', pageWidth / 2, y, { align: 'center' });
  y += 10;

  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(`Date: ${new Date().toLocaleDateString('en-MY', { year: 'numeric', month: 'long', day: 'numeric', hour: '2-digit', minute: '2-digit' })}`, 14, y);
  doc.text('Version: 0.0.1', pageWidth - 14, y, { align: 'right' });
  y += 12;

  doc.setDrawColor(200, 200, 200);
  doc.line(14, y, pageWidth - 14, y);
  y += 8;

  doc.setFontSize(14);
  doc.setTextColor(0, 0, 0);
  doc.text('Hardware Detected', 14, y);
  y += 8;
  doc.setFontSize(10);
  doc.setTextColor(50, 50, 50);

  const lines = [
    `CPU: ${hw.cpu.name} (${hw.cpu.tdp}W)`,
    `GPU: ${hw.gpus[0]?.name || 'None'} (${hw.gpus[0]?.tdp || 0}W)`,
    `RAM: ${hw.ram.totalGB}GB (${hw.ram.sticks} sticks)`,
    `Storage: ${hw.storage.length} drive(s)`,
    `Motherboard: ${hw.motherboard.manufacturer} ${hw.motherboard.model}`,
  ];

  for (const line of lines) {
    doc.text(line, 18, y);
    y += 6;
  }

  y += 4;
  doc.setDrawColor(200, 200, 200);
  doc.line(14, y, pageWidth - 14, y);
  y += 8;

  doc.setFontSize(14);
  doc.setTextColor(0, 0, 0);
  doc.text('Live Power Reading', 14, y);
  y += 8;
  doc.setFontSize(10);
  doc.setTextColor(50, 50, 50);

  const powerLines = [
    `Current: ${power.currentWatts}W`,
    `CPU: ${power.cpuWatts}W (${power.cpuLoadPercent}%)`,
    `GPU: ${power.gpuWatts}W (${power.gpuLoadPercent}%)`,
    `Max: ${power.maxWatts}W`,
  ];

  for (const line of powerLines) {
    doc.text(line, 18, y);
    y += 6;
  }

  y += 4;
  doc.setDrawColor(200, 200, 200);
  doc.line(14, y, pageWidth - 14, y);
  y += 8;

  doc.setFontSize(14);
  doc.setTextColor(0, 0, 0);
  doc.text('Cost Breakdown (TNB Malaysia)', 14, y);
  y += 8;
  doc.setFontSize(10);
  doc.setTextColor(50, 50, 50);

  const costLines = [
    `Rate: RM ${cost.appliedRateRmPerKwh}/kWh (${tariffName})`,
    `Usage: ${cost.dailyUseHours}h/day`,
    `Per Hour: RM ${cost.costPerHour}`,
    `Per Day: RM ${cost.costPerDay}`,
    `Per Month (30 days): RM ${cost.costPerMonth}`,
    `Per Year: RM ${cost.costPerYear}`,
    `Standby Cost: RM ${cost.costPerDayStandby}/day`,
  ];

  for (const line of costLines) {
    doc.text(line, 18, y);
    y += 6;
  }

  y += 4;
  doc.setDrawColor(200, 200, 200);
  doc.line(14, y, pageWidth - 14, y);
  y += 8;

  doc.setFontSize(14);
  doc.setTextColor(0, 0, 0);
  doc.text('TNB Tariff Block Rates', 14, y);
  y += 8;
  doc.setFontSize(10);
  doc.setTextColor(50, 50, 50);

  for (const block of blocks) {
    const range = block.maxKwh !== null ? `${block.minKwh}-${block.maxKwh} kWh` : `${block.minKwh}+ kWh`;
    doc.text(`${block.name} (${range}): ${block.senPerKwh} sen/kWh`, 18, y);
    y += 6;
  }

  y = doc.internal.pageSize.getHeight() - 20;
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text('Generated by Consumptioness v0.0.1', pageWidth / 2, y, { align: 'center' });

  doc.save(`Consumptioness_${Date.now()}.pdf`);
}

export async function exportToExcel(
  hw: HardwareInfo,
  power: PowerData,
  cost: CostBreakdown,
  blocks: TnbTariffBlock[]
) {
  const ExcelJS = await import('exceljs');
  const workbook = new ExcelJS.Workbook();
  const ws = workbook.addWorksheet('Consumptioness Report');

  ws.getCell('A1').value = 'Consumptioness - PC Power Report';
  ws.getCell('A1').font = { bold: true, size: 16 };

  ws.getCell('A3').value = 'Date:';
  ws.getCell('B3').value = new Date().toLocaleDateString('en-MY');

  ws.getCell('A5').value = 'HARDWARE';
  ws.getCell('A5').font = { bold: true };

  ws.getCell('A6').value = 'CPU';
  ws.getCell('B6').value = hw.cpu.name;
  ws.getCell('C6').value = `${hw.cpu.tdp}W`;

  ws.getCell('A7').value = 'GPU';
  ws.getCell('B7').value = hw.gpus[0]?.name || 'None';
  ws.getCell('C7').value = hw.gpus[0] ? `${hw.gpus[0].tdp}W` : '0W';

  ws.getCell('A8').value = 'RAM';
  ws.getCell('B8').value = `${hw.ram.totalGB}GB (${hw.ram.sticks} sticks)`;

  ws.getCell('A9').value = 'Storage';
  ws.getCell('B9').value = `${hw.storage.length} drive(s)`;

  ws.getCell('A11').value = 'LIVE POWER';
  ws.getCell('A11').font = { bold: true };

  ws.getCell('A12').value = 'Current';
  ws.getCell('B12').value = `${Math.round(power.currentWatts)}W`;
  ws.getCell('A13').value = 'CPU Load';
  ws.getCell('B13').value = `${power.cpuLoadPercent}%`;
  ws.getCell('A14').value = 'GPU Load';
  ws.getCell('B14').value = `${power.gpuLoadPercent}%`;
  ws.getCell('A15').value = 'Max Power';
  ws.getCell('B15').value = `${power.maxWatts}W`;

  ws.getCell('A17').value = 'COST (TNB Malaysia)';
  ws.getCell('A17').font = { bold: true };

  ws.getCell('A18').value = 'Rate';
  ws.getCell('B18').value = `RM ${cost.appliedRateRmPerKwh}/kWh`;
  ws.getCell('A19').value = 'Per Hour';
  ws.getCell('B19').value = `RM ${cost.costPerHour}`;
  ws.getCell('A20').value = 'Per Day';
  ws.getCell('B20').value = `RM ${cost.costPerDay}`;
  ws.getCell('A21').value = 'Per Month';
  ws.getCell('B21').value = `RM ${cost.costPerMonth}`;
  ws.getCell('A22').value = 'Per Year';
  ws.getCell('B22').value = `RM ${cost.costPerYear}`;
  ws.getCell('A23').value = 'Standby/Day';
  ws.getCell('B23').value = `RM ${cost.costPerDayStandby}`;

  ws.getCell('A25').value = 'TNB TARIFF BLOCKS';
  ws.getCell('A25').font = { bold: true };

  ws.getCell('A26').value = 'Block';
  ws.getCell('B26').value = 'Range (kWh)';
  ws.getCell('C26').value = 'Rate (sen/kWh)';

  let row = 27;
  for (const block of blocks) {
    ws.getCell(`A${row}`).value = block.name;
    ws.getCell(`B${row}`).value = block.maxKwh !== null ? `${block.minKwh}-${block.maxKwh}` : `${block.minKwh}+`;
    ws.getCell(`C${row}`).value = block.senPerKwh;
    row++;
  }

  ws.columns.forEach(col => {
    if (col) col.width = 20;
  });

  const buffer = await workbook.xlsx.writeBuffer();
  const blob = new Blob([buffer], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `Consumptioness_${Date.now()}.xlsx`;
  a.click();
  URL.revokeObjectURL(url);
}
