using System.IO;
using ClosedXML.Excel;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using Consumptioness.Models;

namespace Consumptioness.Services;

public class ExportService
{
    public ExportService()
    {
        QuestPDF.Settings.License = LicenseType.Community;
    }

    public async Task<string> ExportToPdf(HardwareInfo hw, PowerData live, CostBreakdown cost, TnbTariff tariff)
    {
        var filePath = Path.Combine(Path.GetTempPath(), $"Consumptioness_{DateTime.Now:yyyyMMdd_HHmmss}.pdf");

        await Task.Run(() =>
        {
            Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Size(PageSizes.A4);
                    page.Margin(2, Unit.Centimetre);

                    page.Header().AlignCenter().Text("Consumptioness - PC Power Report")
                        .FontSize(20).Bold().FontColor(Colors.Purple.Darken2);

                    page.Content().Column(col =>
                    {
                        col.Spacing(10);

                        col.Item().Text($"Date: {DateTime.Now:dd MMMM yyyy HH:mm}").FontSize(10);
                        col.Item().Text($"Version: 0.0.1").FontSize(10);

                        col.Item().LineHorizontal(1).LineColor(Colors.Grey.Lighten2);

                        col.Item().Text("Hardware Detected").FontSize(14).Bold();
                        col.Item().Text($"CPU: {hw.Cpu.Name} ({hw.Cpu.TdpWatts}W)");
                        col.Item().Text($"GPU: {(hw.Gpus.Count > 0 ? hw.Gpus[0].Name : "None")} ({(hw.Gpus.Count > 0 ? hw.Gpus[0].TdpWatts : 0)}W)");
                        col.Item().Text($"RAM: {hw.Ram.TotalBytes / (1024*1024*1024)}GB ({hw.Ram.StickCount} sticks)");
                        col.Item().Text($"Storage: {hw.Storage.Count} drive(s)");

                        col.Item().LineHorizontal(1).LineColor(Colors.Grey.Lighten2);

                        col.Item().Text("Live Power Reading").FontSize(14).Bold();
                        col.Item().Text($"Current: {live.CurrentWatts}W");
                        col.Item().Text($"CPU: {live.CpuWatts}W ({live.CpuLoadPercent}%)");
                        col.Item().Text($"GPU: {live.GpuWatts}W ({live.GpuLoadPercent}%)");
                        col.Item().Text($"Max: {live.MaxWatts}W");

                        col.Item().LineHorizontal(1).LineColor(Colors.Grey.Lighten2);

                        col.Item().Text("Cost Breakdown (TNB Malaysia)").FontSize(14).Bold();
                        col.Item().Text($"Rate: RM {cost.AppliedRateRmPerKwh}/kWh ({tariff.Name})");
                        col.Item().Text($"Usage: {cost.DailyUseHours}h/day");
                        col.Item().Text($"Per Hour: RM {cost.CostPerHour}");
                        col.Item().Text($"Per Day: RM {cost.CostPerDay}");
                        col.Item().Text($"Per Month: RM {cost.CostPerMonth}");
                        col.Item().Text($"Per Year: RM {cost.CostPerYear}");
                        col.Item().Text($"Standby Cost: RM {cost.CostPerDayStandby}/day");

                        col.Item().LineHorizontal(1).LineColor(Colors.Grey.Lighten2);

                        col.Item().Text("TNB Tariff Block Rates").FontSize(14).Bold();
                        foreach (var b in tariff.Blocks)
                        {
                            var range = b.MaxKwh.HasValue
                                ? $"{b.MinKwh}-{b.MaxKwh} kWh"
                                : $"{b.MinKwh}+ kWh";
                            col.Item().Text($"  {b.Name} ({range}): {b.SenPerKwh} sen/kWh");
                        }
                    });

                    page.Footer().AlignCenter().Text("Generated by Consumptioness v0.0.1")
                        .FontSize(8).FontColor(Colors.Grey.Medium);
                });
            }).GeneratePdf(filePath);
        });

        return filePath;
    }

    public async Task<string> ExportToExcel(HardwareInfo hw, PowerData live, CostBreakdown cost, TnbTariff tariff)
    {
        var filePath = Path.Combine(Path.GetTempPath(), $"Consumptioness_{DateTime.Now:yyyyMMdd_HHmmss}.xlsx");

        await Task.Run(() =>
        {
            using var workbook = new XLWorkbook();

            var ws = workbook.Worksheets.Add("Consumptioness Report");

            ws.Cell(1, 1).Value = "Consumptioness - PC Power Report";
            ws.Cell(1, 1).Style.Font.Bold = true;
            ws.Cell(1, 1).Style.Font.FontSize = 16;

            ws.Cell(3, 1).Value = "Date:";
            ws.Cell(3, 2).Value = DateTime.Now.ToString("dd MMMM yyyy HH:mm");

            ws.Cell(5, 1).Value = "HARDWARE";
            ws.Cell(5, 1).Style.Font.Bold = true;

            ws.Cell(6, 1).Value = "CPU";
            ws.Cell(6, 2).Value = hw.Cpu.Name;
            ws.Cell(6, 3).Value = $"{hw.Cpu.TdpWatts}W";

            ws.Cell(7, 1).Value = "GPU";
            ws.Cell(7, 2).Value = hw.Gpus.Count > 0 ? hw.Gpus[0].Name : "None";
            ws.Cell(7, 3).Value = hw.Gpus.Count > 0 ? $"{hw.Gpus[0].TdpWatts}W" : "0W";

            ws.Cell(8, 1).Value = "RAM";
            ws.Cell(8, 2).Value = $"{hw.Ram.TotalBytes / (1024*1024*1024)}GB ({hw.Ram.StickCount} sticks)";

            ws.Cell(9, 1).Value = "Storage";
            ws.Cell(9, 2).Value = $"{hw.Storage.Count} drive(s)";

            ws.Cell(11, 1).Value = "LIVE POWER";
            ws.Cell(11, 1).Style.Font.Bold = true;

            ws.Cell(12, 1).Value = "Current";
            ws.Cell(12, 2).Value = $"{live.CurrentWatts}W";
            ws.Cell(13, 1).Value = "CPU Load";
            ws.Cell(13, 2).Value = $"{live.CpuLoadPercent}%";
            ws.Cell(14, 1).Value = "GPU Load";
            ws.Cell(14, 2).Value = $"{live.GpuLoadPercent}%";
            ws.Cell(15, 1).Value = "Max Power";
            ws.Cell(15, 2).Value = $"{live.MaxWatts}W";

            ws.Cell(17, 1).Value = "COST (TNB Malaysia)";
            ws.Cell(17, 1).Style.Font.Bold = true;

            ws.Cell(18, 1).Value = "Rate";
            ws.Cell(18, 2).Value = $"RM {cost.AppliedRateRmPerKwh}/kWh";
            ws.Cell(19, 1).Value = "Per Hour";
            ws.Cell(19, 2).Value = $"RM {cost.CostPerHour}";
            ws.Cell(20, 1).Value = "Per Day";
            ws.Cell(20, 2).Value = $"RM {cost.CostPerDay}";
            ws.Cell(21, 1).Value = "Per Month";
            ws.Cell(21, 2).Value = $"RM {cost.CostPerMonth}";
            ws.Cell(22, 1).Value = "Per Year";
            ws.Cell(22, 2).Value = $"RM {cost.CostPerYear}";
            ws.Cell(23, 1).Value = "Standby/Day";
            ws.Cell(23, 2).Value = $"RM {cost.CostPerDayStandby}";

            ws.Cell(25, 1).Value = "TNB TARIFF BLOCKS";
            ws.Cell(25, 1).Style.Font.Bold = true;

            ws.Cell(26, 1).Value = "Block";
            ws.Cell(26, 2).Value = "Range (kWh)";
            ws.Cell(26, 3).Value = "Rate (sen/kWh)";
            int row = 27;
            foreach (var b in tariff.Blocks)
            {
                ws.Cell(row, 1).Value = b.Name;
                ws.Cell(row, 2).Value = b.MaxKwh.HasValue ? $"{b.MinKwh}-{b.MaxKwh}" : $"{b.MinKwh}+";
                ws.Cell(row, 3).Value = b.SenPerKwh;
                row++;
            }

            ws.Columns().AdjustToContents();
            workbook.SaveAs(filePath);
        });

        return filePath;
    }
}
